<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agency template is required field' => 'Необходимо выбрать шаблон организации',
    'City is required field' => 'Необходимо выборать город',
    'City name is required field' => 'Необходимо заполнить поле «Название города»',
    'City short name is required field' => 'Необходимо заполнить поле «Короткое название города»',
    'Create new agency' => 'Создать новое агенство',
    'Create new organisation by template «{0}»' => 'Создание агенства по шаблону «{0}»',
    'Invalid city' => 'Город не существует или принадлежит другому государству',
    'Rename city' => 'Переименовать город',
    'Rename city {0} to «{1}» ({2})' => 'Переименовать город {0} в «{1}» ({2})',
    'Rename our state to «{0}» ({1})' => 'Переименовать наше государство в «{0}» ({1})',
    'Rename region' => 'Переименовать регион',
    'Rename region {0} to «{1}» ({2})' => 'Переименовать регион {0} в «{1}» ({2})',
    'Rename state' => 'Переименовать государство',
];
