<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agency is required field' => 'Необходимо выбрать агенство',
    'Agency name is required field' => 'Необходимо заполнить поле «Название агенства»',
    'Agency short name is required field' => 'Необходимо заполнить поле «Краткое название агенства»',
    'Agency template is required field' => 'Необходимо выбрать шаблон организации',
    'Anthem is required field' => 'Необходимо заполнить поле «Гимн»',
    'Anthem must be valid SoundCloud link' => 'Гимн должен быть ссылкой на SoundCloud',
    'Change anthem of city {0} to {1}' => 'Изменить гимн города {0} на {1}',
    'Change anthem of region {0} to {1}' => 'Изменить гимн региона {0} на {1}',
    'Change border between regions {0} and {1}' => 'Изменить границы между регионами {0} и {1}',
    'Change capital of region {0} to city {1}' => 'Перенести столицу региона {0} в город {1}',
    'Change city anthem' => 'Изменить гимн города',
    'Change city flag' => 'Изменить флаг города',
    'Change flag of city {0} to {1}' => 'Изменить гимн города {0} на {1}',
    'Change flag of region {0} to {1}' => 'Изменить гимн региона {0} на {1}',
    'Change our state anthem to {0}' => 'Изменить государственный гимн на {0}',
    'Change our state capital to city {0}' => 'Перенести столицу государства в город {0}',
    'Change our state flag to {0}' => 'Изменить государственный флаг на {0}',
    'Change parties politic' => 'Изменить партийную политику',
    'Change parties politic to {0}' => 'Изменить партийную политику на «{0}»',
    'Change region anthem' => 'Изменить гимн региона',
    'Change region capital' => 'Перенести столицу региона',
    'Change region flag' => 'Изменить флаг региона',
    'Change regions border' => 'Изменить границы между регионами',
    'Change state anthem' => 'Изменить государственный гимн',
    'Change state capital' => 'Перенести столицу государства',
    'Change state flag' => 'Изменить государственный флаг',
    'Children region is required field' => 'Необходимо выбрать дочерний регион',
    'City allready is capital' => 'Этот город уже является столицей',
    'City is required field' => 'Необходимо выборать город',
    'City name is required field' => 'Необходимо заполнить поле «Название города»',
    'City short name is required field' => 'Необходимо заполнить поле «Короткое название города»',
    'Create new agency' => 'Создать новое агенство',
    'Create new organisation by template «{0}»' => 'Создание агенства по шаблону «{0}»',
    'First region is required field' => 'Необходимо выбрать первый регион',
    'Flag is required field' => 'Необходимо заполнить поле «Флаг»',
    'Flag must be valid link to image' => 'Флаг должен быть прямой ссылкой на изображение',
    'Implode regions' => 'Объединить регионы',
    'Include region {0} to region {1}' => 'Включить регион {0} в состав региона {1}',
    'Invalid agency' => 'Агенство не существует или принадлежит другому государству',
    'Invalid city' => 'Город не существует или принадлежит другому государству',
    'Invalid region' => 'Регион не существует или принадлежит другому государству',
    'Invalid tiles' => 'Тайлы не существуют или принадлежат другому государству',
    'Main region is required field' => 'Необходимо выбрать материнский регион',
    'Need select tiles' => 'Необходимо выбрать тайлы',
    'Need select tiles for first region' => 'Необходимо выбрать тайлы первого региона',
    'Need select tiles for second region' => 'Необходимо выбрать тайлы второго региона',
    'Parties politic is required field' => 'Необходимо выбрать партийную политику',
    'Parties registration cost is required field' => 'Необходимо заполнить поле «Стоимость регистрации партий»',
    'Region is required field' => 'Необходимо выбрать регион',
    'Region name is required field' => 'Необходимо заполнить поле «Название региона»',
    'Region short name is required field' => 'Необходимо заполнить поле «Краткое название региона»',
    'Rename agency' => 'Переименовать агенство',
    'Rename agency {0} to «{1}» ({2})' => 'Переименовать агенство {0} в «{1}» ({2})',
    'Rename city' => 'Переименовать город',
    'Rename city {0} to «{1}» ({2})' => 'Переименовать город {0} в «{1}» ({2})',
    'Rename our state to «{0}» ({1})' => 'Переименовать наше государство в «{0}» ({1})',
    'Rename region' => 'Переименовать регион',
    'Rename region {0} to «{1}» ({2})' => 'Переименовать регион {0} в «{1}» ({2})',
    'Rename state' => 'Переименовать государство',
    'Ruling party is required field' => 'Необходимо выбрать правящую партию',
    'Seduce new region' => 'Выделить новый регион',
    'Seduce new region «{0}» ({1}) from region {2}' => 'Выделить новый регион «{0}» ({1}) из региона {2}',
    'Select some other region' => 'Выберите другой регион',
    'State name is required field' => 'Необходимо заполнить поле «Название государства»',
    'State short name is required field' => 'Необходимо заполнить поле «Краткое название государства»',
    'Undefined tiles' => 'Неизвестные тайлы',
];
